# Generated by Django 2.2 on 2019-04-25 17:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('heigth', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ability_name', models.CharField(max_length=255)),
            ],
            managers=[
                ('busca', django.db.models.manager.Manager()),
            ],
        ),
    ]
